### ISSUE TITLE
404 | Page Not Found

### ISSUE THREAD

**Issue by jschoedt** [TatsuUkraine/pu-search-example#3]
Hi,
I get this error page when I follow the Build setup. No errors in the console. Any clues?
Thanks

**Comment by TatsuUkraine** [comment]
@jschoedt sorry, my bad, forgot to set root route, in this project currently 2 available routes: /authors and /books

**Comment by TatsuUkraine** [comment]
@jschoedt  #4 should fix it. But overall I have improved version for this scaffold, going to update it when I will have time
